# Generated by Django 3.1.3 on 2022-07-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_auto_20220720_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
