# Generated by Django 3.2.13 on 2022-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0011_auto_20220731_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
