# Generated by Django 3.2.13 on 2022-08-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0012_auto_20220731_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
    ]
